spring:
  application:
    name: zuul
  rabbitmq: 
    host: 192.168.40.133
    port: 5672
    username: admin
    password: admin
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka,http://eureka1:2001/eureka
    
#可默认缺省
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
#降低 hystrix 超时时间，以便测试降级 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500